#!/bin/bash
#
# Morning summary generator for Overnight GSD
#

generate_morning_summary() {
    local summary_file="$OUTPUT_DIR/morning-summary.md"
    local end_time=$(date +%s)
    local duration=$((end_time - START_TIME))
    local hours=$((duration / 3600))
    local minutes=$(((duration % 3600) / 60))

    cat > "$summary_file" <<EOF
# Overnight GSD Summary

**Run ID:** $RUN_ID
**Date:** $(date '+%B %d, %Y')
**Duration:** ${hours}h ${minutes}m
**Started:** $(date -r $START_TIME '+%I:%M %p')
**Ended:** $(date '+%I:%M %p')

---

## Quick Stats

| Metric | Value |
|--------|-------|
| Total Cost | \$${TOTAL_COST} |
| Iterations | $ITERATION |
| Plans Completed | $PLANS_COMPLETED |
| Phases Completed | $PHASES_COMPLETED |
| n8n Workflows Tested | $N8N_WORKFLOWS_TESTED |
| Blockers | ${#BLOCKERS[@]} |

---

## Completed Work

EOF

    if [[ ${#COMPLETED_ITEMS[@]} -eq 0 ]]; then
        echo "_No items completed_" >> "$summary_file"
    else
        for item in "${COMPLETED_ITEMS[@]}"; do
            echo "- ✅ $item" >> "$summary_file"
        done
    fi

    cat >> "$summary_file" <<EOF

---

## Ready for Testing

The following items completed overnight and are ready for your review:

EOF

    # List completed items that need testing
    local has_items=false
    for item in "${COMPLETED_ITEMS[@]}"; do
        if [[ "$item" == GSD* ]]; then
            echo "- [ ] $item - verify functionality works as expected" >> "$summary_file"
            has_items=true
        elif [[ "$item" == n8n* ]]; then
            echo "- [ ] $item - trigger manually and verify output" >> "$summary_file"
            has_items=true
        fi
    done

    if [[ "$has_items" == "false" ]]; then
        echo "_No items ready for testing_" >> "$summary_file"
    fi

    cat >> "$summary_file" <<EOF

---

## Blockers

EOF

    if [[ ${#BLOCKERS[@]} -eq 0 ]]; then
        echo "_No blockers encountered_ :tada:" >> "$summary_file"
    else
        echo "The following issues need your attention:" >> "$summary_file"
        echo "" >> "$summary_file"
        for blocker in "${BLOCKERS[@]}"; do
            echo "### ⚠️ $blocker" >> "$summary_file"
            echo "" >> "$summary_file"
        done
        echo "" >> "$summary_file"
        echo "See \`.overnight/blockers.md\` for full details." >> "$summary_file"
    fi

    cat >> "$summary_file" <<EOF

---

## Cost Breakdown

$(get_cost_summary)

See \`.overnight/cost-report.json\` for detailed per-iteration costs.

---

## Logs

- **Progress Log:** \`.overnight/progress.log\`
- **Iteration Logs:** \`.overnight/iterations/\`
- **Cost Report:** \`.overnight/cost-report.json\`
- **Blockers:** \`.overnight/blockers.md\`

---

## Next Steps

EOF

    if [[ ${#BLOCKERS[@]} -gt 0 ]]; then
        cat >> "$summary_file" <<EOF
1. Review blockers above and resolve them
2. Test completed items listed above
3. Run \`/gsd:progress\` to see current state
4. Continue with next phase when ready
EOF
    else
        cat >> "$summary_file" <<EOF
1. Test completed items listed above
2. Run \`/gsd:progress\` to see current state
3. Consider running another overnight session for remaining work
EOF
    fi

    cat >> "$summary_file" <<EOF

---

*Generated by Overnight GSD at $(date)*
EOF

    log "Morning summary generated: $summary_file"
}
