// Environment Configuration Template
// DO NOT EDIT THIS FILE - Create env-config.local.js for your local values
// This file serves as a template showing all required configuration keys
//
// To use for local development:
// 1. Copy this entire object to js/env-config.local.js
// 2. Update the values with your actual API keys and URLs
// 3. NEVER commit env-config.local.js to git (it's in .gitignore)
// 4. Load env-config.local.js BEFORE this file in your HTML

window.ENV_CONFIG = {
    // ===== STRIPE CONFIGURATION =====
    // Publishable key is safe to expose in frontend code (it's public by design)
    STRIPE_PUBLISHABLE_KEY: 'pk_test_51Rm0oDLD9MaHSRjsQahsZns3p9JW1U38hM5r0WEDIl6j7U2XL1f3zsMKEcQhZ71DO53BgA3TGFbzQW1Gvuz3Ec9s00JgVCzA9C',

    // ===== GOHIGHLEVEL WEBHOOKS =====
    // Webhook URL (no authentication needed, obscured URL is the security mechanism)
    GHL_REGISTRATION_WEBHOOK: 'https://services.leadconnectorhq.com/hooks/MjGEy0pobNT9su2YJqFI/webhook-trigger/8a0aa0b8-52c0-4810-8475-c0e1b82adb70',
    GHL_CONTACT_WEBHOOK: 'https://services.leadconnectorhq.com/hooks/MjGEy0pobNT9su2YJqFI/webhook-trigger/f11dd475-e8a8-442d-a71e-862b25d34937',

    // ===== AIRTABLE TABLE IDs (not secrets) =====
    AIRTABLE_PROGRAMS_TABLE: 'tblFaya3JyTzyAdjJ',
    AIRTABLE_COUPONS_TABLE: 'tblBaUQKmYuIMsVQm',
    AIRTABLE_QUIZ_QUESTIONS_TABLE: 'tblKESCDfq65dWWHy',
    AIRTABLE_QUIZ_ANSWERS_TABLE: 'tbly6vzYhjPbroIIy',
    AIRTABLE_QUIZ_RECOMMENDATIONS_TABLE: 'tblp78ibbqFGYFGKb',
    AIRTABLE_QUIZ_SESSIONS_TABLE: 'tblzXcIgwisfko0WC',
    AIRTABLE_VIEW_ID: 'viwGwK0DuZyjMzsZI',

    // ===== GOOGLE ANALYTICS =====
    GA4_ID: 'G-XXXXXXXXXX'
};
